#!/bin/sh
# Sysupgrade migration: legacy paths → CM5 debug UART (/dev/ttyS2).

. /lib/functions/system.sh

[ "$(board_name)" = "xunlong,orangepi-cm5-base" ] || exit 0
[ -c /dev/ttyS2 ] || exit 0
[ "$(uci -q get mcud.@mcud[0].cm5_uart_migrated)" = "2" ] && exit 0

cur="$(uci -q get mcud.@mcud[0].path)"
case "$cur" in
/dev/ttyUSB0|/dev/ttyUSB1|/dev/ttyS4|'')
	;;
*)
	exit 0
	;;
esac

logger -t mcud-cm5-migrate "setting mcud path to /dev/ttyS2 (debug UART)"
uci -q batch <<-EOF
	set mcud.@mcud[0].path='/dev/ttyS2'
	set mcud.@mcud[0].baud='115200'
	set mcud.@mcud[0].cm5_uart_migrated='2'
	commit mcud
EOF

exit 0
