#!/bin/sh

changed=0

[ -n "$(uci -q get mcud.@mcud[0].screen_timeout)" ] || {
	uci -q set mcud.@mcud[0].screen_timeout=60
	changed=1
}
[ -n "$(uci -q get mcud.@mcud[0].screen_timeout_mode)" ] || {
	uci -q set mcud.@mcud[0].screen_timeout_mode=off
	changed=1
}
[ -n "$(uci -q get mcud.@mcud[0].log_level)" ] || {
	uci -q set mcud.@mcud[0].log_level=info
	changed=1
}
[ -n "$(uci -q get mcud.@mcud[0].debug)" ] || {
	uci -q set mcud.@mcud[0].debug=0
	changed=1
}
[ -n "$(uci -q get mcud.@mcud[0].debug_serial)" ] || {
	uci -q set mcud.@mcud[0].debug_serial=0
	changed=1
}

case "$(board_name 2>/dev/null)" in
xunlong,orangepi-cm5-base)
	if [ -c /dev/ttyS2 ]; then
		cur="$(uci -q get mcud.@mcud[0].path)"
		case "$cur" in
		''|/dev/ttyUSB0|/dev/ttyUSB1|/dev/ttyS4)
			uci -q set mcud.@mcud[0].path='/dev/ttyS2'
			changed=1
			;;
		esac
		[ "$(uci -q get mcud.@mcud[0].baud)" = "115200" ] || {
			uci -q set mcud.@mcud[0].baud=115200
			changed=1
		}
	fi
	;;
esac

[ "$changed" = 1 ] && uci commit mcud

if [ -x /etc/init.d/mcudd ]; then
	/etc/init.d/mcudd enable
fi

exit 0
