upstreams:
  groups:
    default:
      - 1.1.1.1
      - 8.8.8.8

blocking:
  denylists:
    stevenblack:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - stevenblack
  loading:
    strategy: fast
    refreshPeriod: 4h
    cachePath: /var/lib/blocky/lists

queryLog:
  type: csv
  target: /tmp/blocky-logs
  logRetentionDays: 7
  flushInterval: 30s

ports:
  dns: 127.0.0.1:5353
  http: 127.0.0.1:4000

prometheus:
  enable: true
  path: /metrics

statistics:
  enable: true
