#!/bin/sh

uci_write_config() {
	[[ `uci -q get oled.@oled[0].showmenu` -eq 1 ]] && return
	uci -q batch <<-EOF >/dev/null
		set oled.@oled[0].showmenu="1"
		set oled.@oled[0].enable="1"
		set oled.@oled[0].path="$1"
		set oled.@oled[0].chip="$2"
		set oled.@oled[0].rotate="$3"
		set oled.@oled[0].netspeed="$4"
		set oled.@oled[0].netsource="$5"
		set oled.@oled[0].ipifname="br-lan"
		commit oled
EOF
}

. /lib/functions/system.sh

cm5_oled_i2c_path() {
	local dev bus
	for dev in /dev/i2c-*; do
		[ -c "$dev" ] || continue
		bus="${dev#/dev/i2c-}"
		i2cdetect -y "$bus" 2>/dev/null | grep -qE '(^|[^0-9a-f])3c([^0-9a-f]|$)' || continue
		echo "$dev"
		return 0
	done
	return 1
}

case "$(board_name)" in
hinlink,opc-h69k)
	uci_write_config '/dev/i2c-5' 'ssd1306_128x32' 1 1 eth0
	;;
xunlong,orangepi-cm5-base)
	if cm5_path="$(cm5_oled_i2c_path)"; then
		uci_write_config "$cm5_path" 'sh1106_128x64' 0 0 br-lan
	else
		uci -q batch <<-EOF >/dev/null
			set oled.@oled[0].showmenu="1"
			set oled.@oled[0].enable="0"
			set oled.@oled[0].path="/dev/i2c-3"
			set oled.@oled[0].chip="sh1106_128x64"
			set oled.@oled[0].ipifname="br-lan"
			set oled.@oled[0].netsource="br-lan"
			commit oled
EOF
	fi
	;;
esac

if [ "$(uci -q get oled.@oled[0].enable)" = "1" ]; then
	/etc/init.d/oled enable
	/etc/init.d/oled start
fi

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@oled[-1]
	add ucitrack oled
	set ucitrack.@oled[-1].init=oled
	commit ucitrack
EOF

sed -e "/\/etc\/init\.d\/oled/d" -i /etc/crontabs/root && /etc/init.d/cron reload
rm -rf /tmp/luci-*
exit 0
