#!/bin/sh
# Host test for tp-eve-ingest (python json fallback + sqlite3).

set -eu
ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
INGEST="$ROOT/files/usr/sbin/tp-eve-ingest"
FIX="$ROOT/tests/fixtures/eve-alert.jsonl"
DB=$(mktemp)
RULES_DIR=$(mktemp -d)
RULES_DB=$(mktemp)
THRESH=$(mktemp)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH"; rm -rf "$RULES_DIR"' EXIT

command -v sqlite3 >/dev/null || { echo "sqlite3 required"; exit 1; }
command -v python3 >/dev/null || { echo "python3 required"; exit 1; }

sh -n "$INGEST"
sh -n "$ROOT/files/usr/sbin/tp-eventd"
sh -n "$ROOT/files/usr/sbin/tp-rules-index"
sh -n "$ROOT/files/usr/sbin/tp-rules-apply"
sh -n "$ROOT/../suricata/files/usr/sbin/suricata-config-apply"
sh -n "$ROOT/../suricata-etopen/files/usr/sbin/suricata-etopen-fetch"

"$INGEST" "@$FIX" "$DB" 10

n=$(sqlite3 "$DB" 'SELECT COUNT(*) FROM events;')
[ "$n" = 2 ] || { echo "expected 2 alerts, got $n"; sqlite3 "$DB" 'SELECT * FROM events;'; exit 1; }

sid=$(sqlite3 "$DB" 'SELECT sid FROM events ORDER BY id LIMIT 1;')
[ "$sid" = 2100498 ] || { echo "sid $sid"; exit 1; }

cls=$(sqlite3 "$DB" 'SELECT classtype FROM events WHERE sid=2100498;')
[ "$cls" = trojan-activity ] || { echo "class $cls"; exit 1; }

# Ring cap
"$INGEST" "@$FIX" "$DB" 1
n=$(sqlite3 "$DB" 'SELECT COUNT(*) FROM events;')
[ "$n" = 1 ] || { echo "ring cap failed n=$n"; exit 1; }

echo "tp-eve-ingest tests ok"

INDEX="$ROOT/files/usr/sbin/tp-rules-index"
APPLY="$ROOT/files/usr/sbin/tp-rules-apply"
cp "$ROOT/tests/fixtures/sample.rules" "$RULES_DIR/emerging-malware.rules"

sh "$INDEX" "$RULES_DIR" "$RULES_DB"
n=$(sqlite3 "$RULES_DB" 'SELECT COUNT(*) FROM rules;')
[ "$n" = 5 ] || { echo "expected 5 indexed rules, got $n"; sqlite3 "$RULES_DB" 'SELECT sid,msg FROM rules;'; exit 1; }

sid=$(sqlite3 "$RULES_DB" 'SELECT sid FROM rules WHERE sid=2020001;')
[ "$sid" = 2020001 ] || { echo "missing 2020001"; exit 1; }

skip=$(sqlite3 "$RULES_DB" 'SELECT COUNT(*) FROM rules WHERE sid=2020003;')
[ "$skip" = 0 ] || { echo "commented rule was indexed"; exit 1; }

msg=$(sqlite3 "$RULES_DB" "SELECT msg FROM rules WHERE sid=2020004;")
[ "$msg" = "ET TEST Continued" ] || { echo "continuation msg: $msg"; exit 1; }

apos=$(sqlite3 "$RULES_DB" "SELECT msg FROM rules WHERE sid=2020006;")
echo "$apos" | grep -q "Apostrophe" || { echo "apostrophe msg: $apos"; exit 1; }

drop=$(sqlite3 "$RULES_DB" "SELECT action FROM rules WHERE sid=2020005;")
[ "$drop" = drop ] || { echo "drop action $drop"; exit 1; }

PATH="/usr/bin:/bin" sh "$APPLY" "$THRESH"
grep -q 'generated by tp-rules-apply' "$THRESH" || { echo "threshold header missing"; exit 1; }

FAKE=$(mktemp -d)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH"; rm -rf "$RULES_DIR" "$FAKE"' EXIT
cat > "$FAKE/uci" <<'EOF'
#!/bin/sh
case "$*" in
"-q show suricata")
	printf '%s\n' \
		'suricata.s2020001=sid' \
		'suricata.s2020002=sid' \
		'suricata.s2020004=sid' \
		'suricata.s2020005=sid'
	;;
"-q get suricata.s2020001.enabled") echo 0 ;;
"-q get suricata.s2020001.status") echo disabled ;;
"-q get suricata.s2020001.gid") echo 1 ;;
"-q get suricata.s2020001.threshold") ;;
"-q get suricata.s2020002.enabled") echo 1 ;;
"-q get suricata.s2020002.status") echo review ;;
"-q get suricata.s2020002.gid") echo 1 ;;
"-q get suricata.s2020002.threshold") echo 'type limit, track by_src, count 1, seconds 60' ;;
"-q get suricata.s2020004.enabled") echo 1 ;;
"-q get suricata.s2020004.status") echo expired ;;
"-q get suricata.s2020004.gid") echo 1 ;;
"-q get suricata.s2020004.threshold") echo 'type limit, track by_src, count 9, seconds 9' ;;
"-q get suricata.s2020005.enabled") echo 1 ;;
"-q get suricata.s2020005.status") echo enabled ;;
"-q get suricata.s2020005.gid") echo 1 ;;
"-q get suricata.s2020005.threshold") echo 'not a valid threshold' ;;
*) exit 1 ;;
esac
exit 0
EOF
chmod +x "$FAKE/uci"
PATH="$FAKE:/usr/bin:/bin" sh "$APPLY" "$THRESH"
grep -q 'suppress gen_id 1, sig_id 2020001' "$THRESH" || { echo "missing disable suppress"; cat "$THRESH"; exit 1; }
grep -q 'threshold gen_id 1, sig_id 2020002, type limit, track by_src, count 1, seconds 60' "$THRESH" || { echo "missing review threshold"; cat "$THRESH"; exit 1; }
grep -q 'suppress gen_id 1, sig_id 2020004' "$THRESH" || { echo "missing expired suppress"; cat "$THRESH"; exit 1; }
grep -q '2020005' "$THRESH" && { echo "invalid threshold was emitted"; cat "$THRESH"; exit 1; }
grep -q 'sig_id 2020004, type' "$THRESH" && { echo "expired SID still got a threshold"; cat "$THRESH"; exit 1; }

echo "tp-rules-index tests ok"
