#!/bin/sh
# Host test for tp-eve-ingest (python json fallback + sqlite3).

set -eu
ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
INGEST="$ROOT/files/usr/sbin/tp-eve-ingest"
FIX="$ROOT/tests/fixtures/eve-alert.jsonl"
DB=$(mktemp)
RULES_DIR=$(mktemp -d)
RULES_DB=$(mktemp)
THRESH=$(mktemp)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH"; rm -rf "$RULES_DIR"' EXIT

command -v sqlite3 >/dev/null || { echo "sqlite3 required"; exit 1; }
command -v python3 >/dev/null || { echo "python3 required"; exit 1; }

sh -n "$INGEST"
sh -n "$ROOT/files/usr/sbin/tp-eventd"
sh -n "$ROOT/files/usr/sbin/tp-rules-index"
sh -n "$ROOT/files/usr/sbin/tp-rules-apply"
sh -n "$ROOT/../suricata/files/usr/sbin/suricata-config-apply"
sh -n "$ROOT/../suricata-etopen/files/usr/sbin/suricata-etopen-fetch"

"$INGEST" "@$FIX" "$DB" 10

n=$(sqlite3 "$DB" 'SELECT COUNT(*) FROM events;')
[ "$n" = 2 ] || { echo "expected 2 alerts, got $n"; sqlite3 "$DB" 'SELECT * FROM events;'; exit 1; }

sid=$(sqlite3 "$DB" 'SELECT sid FROM events ORDER BY id LIMIT 1;')
[ "$sid" = 2100498 ] || { echo "sid $sid"; exit 1; }

cls=$(sqlite3 "$DB" 'SELECT classtype FROM events WHERE sid=2100498;')
[ "$cls" = trojan-activity ] || { echo "class $cls"; exit 1; }

# Ring cap
"$INGEST" "@$FIX" "$DB" 1
n=$(sqlite3 "$DB" 'SELECT COUNT(*) FROM events;')
[ "$n" = 1 ] || { echo "ring cap failed n=$n"; exit 1; }

echo "tp-eve-ingest tests ok"

INDEX="$ROOT/files/usr/sbin/tp-rules-index"
APPLY="$ROOT/files/usr/sbin/tp-rules-apply"
cp "$ROOT/tests/fixtures/sample.rules" "$RULES_DIR/emerging-malware.rules"

sh "$INDEX" "$RULES_DIR" "$RULES_DB"
n=$(sqlite3 "$RULES_DB" 'SELECT COUNT(*) FROM rules;')
[ "$n" = 5 ] || { echo "expected 5 indexed rules, got $n"; sqlite3 "$RULES_DB" 'SELECT sid,msg FROM rules;'; exit 1; }

sid=$(sqlite3 "$RULES_DB" 'SELECT sid FROM rules WHERE sid=2020001;')
[ "$sid" = 2020001 ] || { echo "missing 2020001"; exit 1; }

skip=$(sqlite3 "$RULES_DB" 'SELECT COUNT(*) FROM rules WHERE sid=2020003;')
[ "$skip" = 0 ] || { echo "commented rule was indexed"; exit 1; }

msg=$(sqlite3 "$RULES_DB" "SELECT msg FROM rules WHERE sid=2020004;")
[ "$msg" = "ET TEST Continued" ] || { echo "continuation msg: $msg"; exit 1; }

apos=$(sqlite3 "$RULES_DB" "SELECT msg FROM rules WHERE sid=2020006;")
echo "$apos" | grep -q "Apostrophe" || { echo "apostrophe msg: $apos"; exit 1; }

drop=$(sqlite3 "$RULES_DB" "SELECT action FROM rules WHERE sid=2020005;")
[ "$drop" = drop ] || { echo "drop action $drop"; exit 1; }

PATH="/usr/bin:/bin" sh "$APPLY" "$THRESH"
grep -q 'generated by tp-rules-apply' "$THRESH" || { echo "threshold header missing"; exit 1; }

echo "tp-rules-index tests ok"
