#!/bin/sh
# Host test for tp-eve-ingest (python json fallback + sqlite3).

set -eu
ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
INGEST="$ROOT/files/usr/sbin/tp-eve-ingest"
FIX="$ROOT/tests/fixtures/eve-alert.jsonl"
DB=$(mktemp)
RULES_DIR=$(mktemp -d)
RULES_DB=$(mktemp)
THRESH=$(mktemp)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH"; rm -rf "$RULES_DIR"' EXIT

command -v sqlite3 >/dev/null || { echo "sqlite3 required"; exit 1; }
command -v python3 >/dev/null || { echo "python3 required"; exit 1; }

sh -n "$INGEST"
sh -n "$ROOT/files/usr/sbin/tp-eventd"
sh -n "$ROOT/files/usr/sbin/tp-rules-index"
sh -n "$ROOT/files/usr/sbin/tp-rules-apply"
sh -n "$ROOT/files/usr/sbin/tp-policy-apply"
sh -n "$ROOT/../suricata/files/usr/sbin/suricata-config-apply"
sh -n "$ROOT/../suricata-etopen/files/usr/sbin/suricata-etopen-fetch"

"$INGEST" "@$FIX" "$DB" 10

n=$(sqlite3 "$DB" 'SELECT COUNT(*) FROM events;')
[ "$n" = 2 ] || { echo "expected 2 alerts, got $n"; sqlite3 "$DB" 'SELECT * FROM events;'; exit 1; }

sid=$(sqlite3 "$DB" 'SELECT sid FROM events ORDER BY id LIMIT 1;')
[ "$sid" = 2100498 ] || { echo "sid $sid"; exit 1; }

cls=$(sqlite3 "$DB" 'SELECT classtype FROM events WHERE sid=2100498;')
[ "$cls" = trojan-activity ] || { echo "class $cls"; exit 1; }

# Ring cap
"$INGEST" "@$FIX" "$DB" 1
n=$(sqlite3 "$DB" 'SELECT COUNT(*) FROM events;')
[ "$n" = 1 ] || { echo "ring cap failed n=$n"; exit 1; }

echo "tp-eve-ingest tests ok"

INDEX="$ROOT/files/usr/sbin/tp-rules-index"
APPLY="$ROOT/files/usr/sbin/tp-rules-apply"
cp "$ROOT/tests/fixtures/sample.rules" "$RULES_DIR/emerging-malware.rules"

sh "$INDEX" "$RULES_DIR" "$RULES_DB"
n=$(sqlite3 "$RULES_DB" 'SELECT COUNT(*) FROM rules;')
[ "$n" = 5 ] || { echo "expected 5 indexed rules, got $n"; sqlite3 "$RULES_DB" 'SELECT sid,msg FROM rules;'; exit 1; }

sid=$(sqlite3 "$RULES_DB" 'SELECT sid FROM rules WHERE sid=2020001;')
[ "$sid" = 2020001 ] || { echo "missing 2020001"; exit 1; }

skip=$(sqlite3 "$RULES_DB" 'SELECT COUNT(*) FROM rules WHERE sid=2020003;')
[ "$skip" = 0 ] || { echo "commented rule was indexed"; exit 1; }

msg=$(sqlite3 "$RULES_DB" "SELECT msg FROM rules WHERE sid=2020004;")
[ "$msg" = "ET TEST Continued" ] || { echo "continuation msg: $msg"; exit 1; }

apos=$(sqlite3 "$RULES_DB" "SELECT msg FROM rules WHERE sid=2020006;")
echo "$apos" | grep -q "Apostrophe" || { echo "apostrophe msg: $apos"; exit 1; }

drop=$(sqlite3 "$RULES_DB" "SELECT action FROM rules WHERE sid=2020005;")
[ "$drop" = drop ] || { echo "drop action $drop"; exit 1; }

PATH="/usr/bin:/bin" sh "$APPLY" "$THRESH"
grep -q 'generated by tp-rules-apply' "$THRESH" || { echo "threshold header missing"; exit 1; }

FAKE=$(mktemp -d)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH"; rm -rf "$RULES_DIR" "$FAKE"' EXIT
cat > "$FAKE/uci" <<'EOF'
#!/bin/sh
case "$*" in
"-q show suricata")
	printf '%s\n' \
		'suricata.s2020001=sid' \
		'suricata.s2020002=sid' \
		'suricata.s2020004=sid' \
		'suricata.s2020005=sid'
	;;
"-q get suricata.s2020001.enabled") echo 0 ;;
"-q get suricata.s2020001.status") echo disabled ;;
"-q get suricata.s2020001.gid") echo 1 ;;
"-q get suricata.s2020001.threshold") ;;
"-q get suricata.s2020002.enabled") echo 1 ;;
"-q get suricata.s2020002.status") echo review ;;
"-q get suricata.s2020002.gid") echo 1 ;;
"-q get suricata.s2020002.threshold") echo 'type limit, track by_src, count 1, seconds 60' ;;
"-q get suricata.s2020004.enabled") echo 1 ;;
"-q get suricata.s2020004.status") echo expired ;;
"-q get suricata.s2020004.gid") echo 1 ;;
"-q get suricata.s2020004.threshold") echo 'type limit, track by_src, count 9, seconds 9' ;;
"-q get suricata.s2020005.enabled") echo 1 ;;
"-q get suricata.s2020005.status") echo enabled ;;
"-q get suricata.s2020005.gid") echo 1 ;;
"-q get suricata.s2020005.threshold") echo 'not a valid threshold' ;;
*) exit 1 ;;
esac
exit 0
EOF
chmod +x "$FAKE/uci"
PATH="$FAKE:/usr/bin:/bin" sh "$APPLY" "$THRESH"
grep -q 'suppress gen_id 1, sig_id 2020001' "$THRESH" || { echo "missing disable suppress"; cat "$THRESH"; exit 1; }
grep -q 'threshold gen_id 1, sig_id 2020002, type limit, track by_src, count 1, seconds 60' "$THRESH" || { echo "missing review threshold"; cat "$THRESH"; exit 1; }
grep -q 'suppress gen_id 1, sig_id 2020004' "$THRESH" || { echo "missing expired suppress"; cat "$THRESH"; exit 1; }
grep -q '2020005' "$THRESH" && { echo "invalid threshold was emitted"; cat "$THRESH"; exit 1; }
grep -q 'sig_id 2020004, type' "$THRESH" && { echo "expired SID still got a threshold"; cat "$THRESH"; exit 1; }

PASS_FAKE=$(mktemp -d)
PASS_THRESH=$(mktemp)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH" "$POL_META" "$PASS_THRESH"; rm -rf "$RULES_DIR" "$FAKE" "$POL_FAKE" "$POL_OUT" "$PASS_FAKE"' EXIT
cat > "$PASS_FAKE/uci" <<'EOF'
#!/bin/sh
case "$*" in
"-q show suricata")
	printf '%s\n' 'suricata.@suppress[0]=suppress'
	;;
"-q get suricata.@suppress[0]") echo suppress ;;
"-q get suricata.@suppress[0].sid") echo 2000354 ;;
"-q get suricata.@suppress[0].gid") echo 1 ;;
"-q get suricata.@suppress[0].track") echo by_src ;;
"-q get suricata.@suppress[0].ip") echo 192.168.8.50 ;;
"-q get suricata.@suppress[1]") exit 1 ;;
"-q get suricata.pass.local_nets") echo 0 ;;
"-q get suricata.pass.wan_gateway") echo 0 ;;
"-q get suricata.pass.wan_dns") echo 0 ;;
"-q get suricata.pass.vpn_addrs") echo 0 ;;
"-q get suricata.pass.ip") echo '203.0.113.10' ;;
*) exit 1 ;;
esac
exit 0
EOF
chmod +x "$PASS_FAKE/uci"
PATH="$PASS_FAKE:/usr/bin:/bin" sh "$APPLY" "$PASS_THRESH"
grep -q 'suppress gen_id 1, sig_id 2000354, track by_src, ip 192.168.8.50' "$PASS_THRESH" || { echo "missing host suppress"; cat "$PASS_THRESH"; exit 1; }
grep -q 'suppress gen_id 1, track by_src, ip 203.0.113.10' "$PASS_THRESH" || { echo "missing pass-list ip"; cat "$PASS_THRESH"; exit 1; }

POLICY="$ROOT/files/usr/sbin/tp-policy-apply"
POL_FAKE=$(mktemp -d)
POL_OUT=$(mktemp -d)
POL_META=$(mktemp)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH" "$POL_META" "$PASS_THRESH"; rm -rf "$RULES_DIR" "$FAKE" "$POL_FAKE" "$POL_OUT" "$PASS_FAKE"' EXIT
cat > "$POL_FAKE/uci" <<'EOF'
#!/bin/sh
case "$*" in
"-q get suricata.main.rule_profile") echo small ;;
"-q show suricata")
	printf '%s\n' \
		'suricata.@classtype[0]=classtype' \
		'suricata.s2020001=sid'
	;;
"-q get suricata.@classtype[0].name") echo trojan-activity ;;
"-q get suricata.@classtype[0].action") echo drop ;;
"-q get suricata.s2020001.enabled") echo 0 ;;
"-q get suricata.s2020001.status") echo disabled ;;
"-q get suricata.s2020001.action") ;;
*) exit 1 ;;
esac
exit 0
EOF
chmod +x "$POL_FAKE/uci"
PATH="$POL_FAKE:/usr/bin:/bin" sh "$POLICY" "$RULES_DIR" "$POL_META" "$POL_OUT"
grep -q "DIR=$POL_OUT" "$POL_META" || { echo "policy meta DIR wrong"; cat "$POL_META"; exit 1; }
grep -q 'FILE=emerging-malware.rules' "$POL_META" || { echo "policy meta missing file"; cat "$POL_META"; exit 1; }
grep -q 'drop http' "$POL_OUT/emerging-malware.rules" || { echo "classtype drop not applied"; cat "$POL_OUT/emerging-malware.rules"; exit 1; }
grep -q 'sid:2020001' "$POL_OUT/emerging-malware.rules" && { echo "disabled SID still emitted"; cat "$POL_OUT/emerging-malware.rules"; exit 1; }

echo "tp-rules-index tests ok"

NOTIFY="$ROOT/files/usr/sbin/tp-notify"
sh -n "$NOTIFY"

NOTIFY_FAKE=$(mktemp -d)
NOTIFY_STATE=$(mktemp -d)
trap 'rm -f "$DB" "$RULES_DB" "$THRESH" "$POL_META" "$PASS_THRESH"; rm -rf "$RULES_DIR" "$FAKE" "$POL_FAKE" "$POL_OUT" "$PASS_FAKE" "$NOTIFY_FAKE" "$NOTIFY_STATE"' EXIT

write_notify_uci() {
	# $1 = extra get cases (optional file of case arms)
	cat > "$NOTIFY_FAKE/uci" <<'UCI'
#!/bin/sh
case "$*" in
"-q show suricata")
	printf '%s\n' 'suricata.n_telegram=notify' 'suricata.n_hook=notify'
	;;
"-q get suricata.n_telegram.enabled") echo 1 ;;
"-q get suricata.n_telegram.type") echo telegram ;;
"-q get suricata.n_telegram.bot_token") echo '123456:AA-SECRET-TOKEN' ;;
"-q get suricata.n_telegram.chat_id") echo 999 ;;
"-q get suricata.n_telegram.min_severity") echo 1 ;;
"-q get suricata.n_telegram.mode") echo realtime ;;
"-q get suricata.n_telegram.rate_limit") echo 12 ;;
"-q get suricata.n_telegram.include_lan") echo 1 ;;
"-q get suricata.n_telegram.classtype") ;;
"-q get suricata.n_telegram.sid_allow") ;;
"-q get suricata.n_telegram.sid_deny") ;;
"-q get suricata.n_telegram.interval") echo 3600 ;;
"-q get suricata.n_hook.enabled") echo 1 ;;
"-q get suricata.n_hook.type") echo webhook ;;
"-q get suricata.n_hook.url") echo 'https://example.invalid/hook' ;;
"-q get suricata.n_hook.header") ;;
"-q get suricata.n_hook.min_severity") echo 1 ;;
"-q get suricata.n_hook.mode") echo realtime ;;
"-q get suricata.n_hook.rate_limit") echo 12 ;;
"-q get suricata.n_hook.include_lan") echo 1 ;;
"-q get suricata.n_hook.classtype") ;;
"-q get suricata.n_hook.sid_allow") ;;
"-q get suricata.n_hook.sid_deny") ;;
"-q get suricata.n_hook.interval") echo 3600 ;;
"-q get system.@system[0].hostname") echo testhost ;;
*) exit 0 ;;
esac
exit 0
UCI
	chmod +x "$NOTIFY_FAKE/uci"
}

run_notify() {
	rm -rf "$NOTIFY_STATE"
	mkdir -p "$NOTIFY_STATE"
	PATH="$NOTIFY_FAKE:/usr/bin:/bin" \
		TP_NOTIFY_DRY_RUN=1 \
		TP_NOTIFY_STATE="$NOTIFY_STATE" \
		TP_NOTIFY_HOST=testhost \
		TP_NOTIFY_NOW=1700000000 \
		"$NOTIFY" "$@"
}

write_notify_uci
ALERT1=$(sed -n '2p' "$FIX")
ALERT2=$(sed -n '3p' "$FIX")
STATS=$(sed -n '1p' "$FIX")

out=$(printf '%s\n' "$STATS" | run_notify)
echo "$out" | grep -q SEND && { echo "stats line should not notify"; echo "$out"; exit 1; }

out=$(printf '%s\n' "$ALERT1" | run_notify)
echo "$out" | grep -q 'SEND telegram chat_id=999' || { echo "missing telegram send"; echo "$out"; exit 1; }
echo "$out" | grep -q 'SID 2100498' || { echo "missing sid in body"; echo "$out"; exit 1; }
echo "$out" | grep -q 'AA-SECRET-TOKEN' && { echo "token leaked"; echo "$out"; exit 1; }
echo "$out" | grep -q 'SEND webhook' || { echo "missing webhook send"; echo "$out"; exit 1; }
echo "$out" | grep -q '"source":"suricata"' || { echo "webhook payload missing source"; echo "$out"; exit 1; }
echo "$out" | grep -q 'event_type' && { echo "raw eve leaked to webhook"; echo "$out"; exit 1; }

st=$(PATH="$NOTIFY_FAKE:/usr/bin:/bin" TP_NOTIFY_STATE="$NOTIFY_STATE" TP_NOTIFY_DRY_RUN=1 "$NOTIFY" --status)
echo "$st" | grep -q '"sent":1' || { echo "status sent missing"; echo "$st"; exit 1; }
echo "$st" | grep -q SECRET && { echo "status leaked secret"; echo "$st"; exit 1; }

# severity filter: min 1 skips severity 3
SEV3='{"timestamp":"2026-08-31T12:00:03.000000+0000","event_type":"alert","src_ip":"203.0.113.10","src_port":1,"dest_ip":"192.168.8.50","dest_port":2,"proto":"TCP","alert":{"gid":1,"signature_id":9,"signature":"low","category":"not-suspicious","severity":3}}'
out=$(printf '%s\n' "$SEV3" | run_notify)
echo "$out" | grep -q SEND && { echo "severity 3 should be skipped"; echo "$out"; exit 1; }

# classtype filter on telegram only — rewrite uci
cat > "$NOTIFY_FAKE/uci" <<'UCI'
#!/bin/sh
case "$*" in
"-q show suricata") echo 'suricata.n_telegram=notify' ;;
"-q get suricata.n_telegram.enabled") echo 1 ;;
"-q get suricata.n_telegram.type") echo telegram ;;
"-q get suricata.n_telegram.bot_token") echo tok ;;
"-q get suricata.n_telegram.chat_id") echo 1 ;;
"-q get suricata.n_telegram.min_severity") echo 1 ;;
"-q get suricata.n_telegram.mode") echo realtime ;;
"-q get suricata.n_telegram.rate_limit") echo 12 ;;
"-q get suricata.n_telegram.include_lan") echo 1 ;;
"-q get suricata.n_telegram.classtype") echo web-application-attack ;;
"-q get suricata.n_telegram.sid_allow") ;;
"-q get suricata.n_telegram.sid_deny") ;;
"-q get suricata.n_telegram.interval") echo 3600 ;;
*) exit 0 ;;
esac
exit 0
UCI
chmod +x "$NOTIFY_FAKE/uci"
out=$(printf '%s\n' "$ALERT1" | run_notify)
echo "$out" | grep -q SEND && { echo "classtype filter should skip trojan"; echo "$out"; exit 1; }
out=$(printf '%s\n' "$ALERT2" | run_notify)
echo "$out" | grep -q SEND || { echo "classtype filter should allow web-application-attack"; echo "$out"; exit 1; }

# sid deny
cat > "$NOTIFY_FAKE/uci" <<'UCI'
#!/bin/sh
case "$*" in
"-q show suricata") echo 'suricata.n_telegram=notify' ;;
"-q get suricata.n_telegram.enabled") echo 1 ;;
"-q get suricata.n_telegram.type") echo telegram ;;
"-q get suricata.n_telegram.bot_token") echo tok ;;
"-q get suricata.n_telegram.chat_id") echo 1 ;;
"-q get suricata.n_telegram.min_severity") echo 1 ;;
"-q get suricata.n_telegram.mode") echo realtime ;;
"-q get suricata.n_telegram.rate_limit") echo 12 ;;
"-q get suricata.n_telegram.include_lan") echo 1 ;;
"-q get suricata.n_telegram.classtype") ;;
"-q get suricata.n_telegram.sid_allow") ;;
"-q get suricata.n_telegram.sid_deny") echo 2100498 ;;
"-q get suricata.n_telegram.interval") echo 3600 ;;
*) exit 0 ;;
esac
exit 0
UCI
chmod +x "$NOTIFY_FAKE/uci"
out=$(printf '%s\n' "$ALERT1" | run_notify)
echo "$out" | grep -q SEND && { echo "sid deny failed"; echo "$out"; exit 1; }

# rate limit 1
cat > "$NOTIFY_FAKE/uci" <<'UCI'
#!/bin/sh
case "$*" in
"-q show suricata") echo 'suricata.n_telegram=notify' ;;
"-q get suricata.n_telegram.enabled") echo 1 ;;
"-q get suricata.n_telegram.type") echo telegram ;;
"-q get suricata.n_telegram.bot_token") echo tok ;;
"-q get suricata.n_telegram.chat_id") echo 1 ;;
"-q get suricata.n_telegram.min_severity") echo 1 ;;
"-q get suricata.n_telegram.mode") echo realtime ;;
"-q get suricata.n_telegram.rate_limit") echo 1 ;;
"-q get suricata.n_telegram.include_lan") echo 1 ;;
"-q get suricata.n_telegram.classtype") ;;
"-q get suricata.n_telegram.sid_allow") ;;
"-q get suricata.n_telegram.sid_deny") ;;
"-q get suricata.n_telegram.interval") echo 3600 ;;
*) exit 0 ;;
esac
exit 0
UCI
chmod +x "$NOTIFY_FAKE/uci"
rm -rf "$NOTIFY_STATE"
mkdir -p "$NOTIFY_STATE"
PATH="$NOTIFY_FAKE:/usr/bin:/bin" TP_NOTIFY_DRY_RUN=1 TP_NOTIFY_STATE="$NOTIFY_STATE" TP_NOTIFY_HOST=testhost TP_NOTIFY_NOW=1700000000 \
	"$NOTIFY" "$ALERT1" >/dev/null
out=$(PATH="$NOTIFY_FAKE:/usr/bin:/bin" TP_NOTIFY_DRY_RUN=1 TP_NOTIFY_STATE="$NOTIFY_STATE" TP_NOTIFY_HOST=testhost TP_NOTIFY_NOW=1700000000 \
	"$NOTIFY" "$ALERT2")
echo "$out" | grep -q SEND && { echo "rate limit should suppress second"; echo "$out"; exit 1; }
st=$(PATH="$NOTIFY_FAKE:/usr/bin:/bin" TP_NOTIFY_STATE="$NOTIFY_STATE" "$NOTIFY" --status)
echo "$st" | grep -q '"suppressed":1' || { echo "suppressed counter"; echo "$st"; exit 1; }

# digest interval 0
cat > "$NOTIFY_FAKE/uci" <<'UCI'
#!/bin/sh
case "$*" in
"-q show suricata") echo 'suricata.n_telegram=notify' ;;
"-q get suricata.n_telegram.enabled") echo 1 ;;
"-q get suricata.n_telegram.type") echo telegram ;;
"-q get suricata.n_telegram.bot_token") echo tok ;;
"-q get suricata.n_telegram.chat_id") echo 1 ;;
"-q get suricata.n_telegram.min_severity") echo 1 ;;
"-q get suricata.n_telegram.mode") echo digest ;;
"-q get suricata.n_telegram.rate_limit") echo 12 ;;
"-q get suricata.n_telegram.include_lan") echo 1 ;;
"-q get suricata.n_telegram.classtype") ;;
"-q get suricata.n_telegram.sid_allow") ;;
"-q get suricata.n_telegram.sid_deny") ;;
"-q get suricata.n_telegram.interval") echo 0 ;;
*) exit 0 ;;
esac
exit 0
UCI
chmod +x "$NOTIFY_FAKE/uci"
out=$(printf '%s\n%s\n' "$ALERT1" "$ALERT2" | run_notify)
echo "$out" | grep -q digest || { echo "digest body missing"; echo "$out"; exit 1; }
echo "$out" | grep -c 'SEND telegram' | grep -q '^[12]$' || { echo "digest send count"; echo "$out"; exit 1; }

# include_lan redaction
cat > "$NOTIFY_FAKE/uci" <<'UCI'
#!/bin/sh
case "$*" in
"-q show suricata") echo 'suricata.n_telegram=notify' ;;
"-q get suricata.n_telegram.enabled") echo 1 ;;
"-q get suricata.n_telegram.type") echo telegram ;;
"-q get suricata.n_telegram.bot_token") echo tok ;;
"-q get suricata.n_telegram.chat_id") echo 1 ;;
"-q get suricata.n_telegram.min_severity") echo 1 ;;
"-q get suricata.n_telegram.mode") echo realtime ;;
"-q get suricata.n_telegram.rate_limit") echo 12 ;;
"-q get suricata.n_telegram.include_lan") echo 0 ;;
"-q get suricata.n_telegram.classtype") ;;
"-q get suricata.n_telegram.sid_allow") ;;
"-q get suricata.n_telegram.sid_deny") ;;
"-q get suricata.n_telegram.interval") echo 3600 ;;
*) exit 0 ;;
esac
exit 0
UCI
chmod +x "$NOTIFY_FAKE/uci"
out=$(printf '%s\n' "$ALERT1" | run_notify)
echo "$out" | grep -q '192.168.8.0' || { echo "lan not redacted"; echo "$out"; exit 1; }
echo "$out" | grep -q '192.168.8.50' && { echo "lan ip leaked"; echo "$out"; exit 1; }

# disabled
cat > "$NOTIFY_FAKE/uci" <<'UCI'
#!/bin/sh
case "$*" in
"-q show suricata") echo 'suricata.n_telegram=notify' ;;
"-q get suricata.n_telegram.enabled") echo 0 ;;
"-q get suricata.n_telegram.type") echo telegram ;;
"-q get suricata.n_telegram.bot_token") echo tok ;;
"-q get suricata.n_telegram.chat_id") echo 1 ;;
"-q get suricata.n_telegram.min_severity") echo 1 ;;
"-q get suricata.n_telegram.mode") echo realtime ;;
"-q get suricata.n_telegram.rate_limit") echo 12 ;;
"-q get suricata.n_telegram.include_lan") echo 1 ;;
"-q get suricata.n_telegram.classtype") ;;
"-q get suricata.n_telegram.sid_allow") ;;
"-q get suricata.n_telegram.sid_deny") ;;
"-q get suricata.n_telegram.interval") echo 3600 ;;
*) exit 0 ;;
esac
exit 0
UCI
chmod +x "$NOTIFY_FAKE/uci"
out=$(printf '%s\n' "$ALERT1" | run_notify)
echo "$out" | grep -q SEND && { echo "disabled channel sent"; echo "$out"; exit 1; }

echo "tp-notify tests ok"

