#!/bin/sh
# CM5 USERKEY / MaskROM → mcudd page navigation (replaces 99-oled).
# Invoked from cm5-button-scripts via hotplug-call button.

[ "$ACTION" = "pressed" ] || exit 0

nav=$(uci -q get mcud.@mcud[0].menu_nav_button); [ -z "$nav" ] && nav=BTN_2
sel=$(uci -q get mcud.@mcud[0].menu_select_button); [ -z "$sel" ] && sel=wps

case "$BUTTON" in
"$sel")
	[ "$sel" != "none" ] && /usr/lib/mcud/mcud-event.sh next
	;;
"$nav")
	[ "$nav" != "none" ] && /usr/lib/mcud/mcud-event.sh prev
	;;
esac

exit 0
